#!/usr/bin/env bash

NAME="James"
echo "Hello $NAME! The Config is being installed"

# Symlinks

ln .vimrc ~/.vimrc 
ln .Xresources ~/.Xresources 
ln .zshrc ~/.zshrc
ln .tmux.conf ~/.tmux.conf

# zsh

# I know this is OS specific and thats a problem but sorry 
sudo apt install zsh
chsh -s $(which zsh)

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# nvim setup

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.config/nvim/
ln ~/.vimrc ~/.config/nvim/init.vim

# Done

echo "Ok $NAME! I think that is all set up for you now :)"
